name: Ensure documentation is up-to-date
on: [push, pull_request]

concurrency: ci-${{ github.ref }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - run: git checkout HEAD^

            - name: Install node_modules
              run: yarn

            - name: Generate docs
              run: yarn generate-doc

            - name: Commit changes
              uses: EndBug/add-and-commit@v9
              if: ${{ github.ref == 'refs/heads/master' }}
              with:
                  author_name: high5-bot
                  author_email: me+high5@dunklestoast.de
                  message: 'docs: update documentation'
                  add: '.'
                  push: true
